# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-19 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='something about this author'),
            preserve_default=False,
        ),
    ]
